version: "3.9"
services:
  graphql:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: markesiano
      MONGO_INITDB_ROOT_PASSWORD: markesiano123
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  



